import React from 'react';
import ReactDOM from 'react-dom/client';
function Country(props) {
    return (<div className="col-lg-4">
        <div className="card shadow">
            <div className="card-body">
                <table className="table">
                    <tbody><tr>
                        <td width="40%">
                            <img src={props.flag} className="img-fluid img-thumbnail" />
                        </td>
                        <td>
                            <h4>{props.name}</h4>
                            <ul className="list-group list-group-flush">
                                <li className="list-group-item">Capital :- {props.capital}</li>
                               
                                <li className="list-group-item">Continent : {props.continent}</li>
                            </ul>
                        </td>
                    </tr>
                    </tbody></table>
            </div>
        </div>
    </div>);
}
function World() {
    // Country Data Array
    // Contains 195 countries with name, capital, continent, and flag image URL (flagcdn.com)
    // Usage: import { countries } from './countries.js';

    const countries = [
        { name: "Afghanistan", capital: "Kabul", continent: "Asia", flag: "https://flagcdn.com/af.svg" },
        { name: "Albania", capital: "Tirana", continent: "Europe", flag: "https://flagcdn.com/al.svg" },
        { name: "Algeria", capital: "Algiers", continent: "Africa", flag: "https://flagcdn.com/dz.svg" },
        { name: "Andorra", capital: "Andorra la Vella", continent: "Europe", flag: "https://flagcdn.com/ad.svg" },
        { name: "Angola", capital: "Luanda", continent: "Africa", flag: "https://flagcdn.com/ao.svg" },
        { name: "Antigua and Barbuda", capital: "Saint John's", continent: "North America", flag: "https://flagcdn.com/ag.svg" },
        { name: "Argentina", capital: "Buenos Aires", continent: "South America", flag: "https://flagcdn.com/ar.svg" },
        { name: "Armenia", capital: "Yerevan", continent: "Asia", flag: "https://flagcdn.com/am.svg" },
        { name: "Australia", capital: "Canberra", continent: "Oceania", flag: "https://flagcdn.com/au.svg" },
        { name: "Austria", capital: "Vienna", continent: "Europe", flag: "https://flagcdn.com/at.svg" },
        { name: "Azerbaijan", capital: "Baku", continent: "Asia", flag: "https://flagcdn.com/az.svg" },
        { name: "Bahamas", capital: "Nassau", continent: "North America", flag: "https://flagcdn.com/bs.svg" },
        { name: "Bahrain", capital: "Manama", continent: "Asia", flag: "https://flagcdn.com/bh.svg" },
        { name: "Bangladesh", capital: "Dhaka", continent: "Asia", flag: "https://flagcdn.com/bd.svg" },
        { name: "Barbados", capital: "Bridgetown", continent: "North America", flag: "https://flagcdn.com/bb.svg" },
        { name: "Belarus", capital: "Minsk", continent: "Europe", flag: "https://flagcdn.com/by.svg" },
        { name: "Belgium", capital: "Brussels", continent: "Europe", flag: "https://flagcdn.com/be.svg" },
        { name: "Belize", capital: "Belmopan", continent: "North America", flag: "https://flagcdn.com/bz.svg" },
        { name: "Benin", capital: "Porto-Novo", continent: "Africa", flag: "https://flagcdn.com/bj.svg" },
        { name: "Bhutan", capital: "Thimphu", continent: "Asia", flag: "https://flagcdn.com/bt.svg" },
        { name: "Bolivia", capital: "Sucre", continent: "South America", flag: "https://flagcdn.com/bo.svg" },
        { name: "Bosnia and Herzegovina", capital: "Sarajevo", continent: "Europe", flag: "https://flagcdn.com/ba.svg" },
        { name: "Botswana", capital: "Gaborone", continent: "Africa", flag: "https://flagcdn.com/bw.svg" },
        { name: "Brazil", capital: "Brasília", continent: "South America", flag: "https://flagcdn.com/br.svg" },
        { name: "Brunei", capital: "Bandar Seri Begawan", continent: "Asia", flag: "https://flagcdn.com/bn.svg" },
        { name: "Bulgaria", capital: "Sofia", continent: "Europe", flag: "https://flagcdn.com/bg.svg" },
        { name: "Burkina Faso", capital: "Ouagadougou", continent: "Africa", flag: "https://flagcdn.com/bf.svg" },
        { name: "Burundi", capital: "Gitega", continent: "Africa", flag: "https://flagcdn.com/bi.svg" },
        { name: "Cambodia", capital: "Phnom Penh", continent: "Asia", flag: "https://flagcdn.com/kh.svg" },
        { name: "Cameroon", capital: "Yaoundé", continent: "Africa", flag: "https://flagcdn.com/cm.svg" },
        { name: "Canada", capital: "Ottawa", continent: "North America", flag: "https://flagcdn.com/ca.svg" },
        { name: "Cape Verde", capital: "Praia", continent: "Africa", flag: "https://flagcdn.com/cv.svg" },
        { name: "Central African Republic", capital: "Bangui", continent: "Africa", flag: "https://flagcdn.com/cf.svg" },
        { name: "Chad", capital: "N'Djamena", continent: "Africa", flag: "https://flagcdn.com/td.svg" },
        { name: "Chile", capital: "Santiago", continent: "South America", flag: "https://flagcdn.com/cl.svg" },
        { name: "China", capital: "Beijing", continent: "Asia", flag: "https://flagcdn.com/cn.svg" },
        { name: "Colombia", capital: "Bogotá", continent: "South America", flag: "https://flagcdn.com/co.svg" },
        { name: "Comoros", capital: "Moroni", continent: "Africa", flag: "https://flagcdn.com/km.svg" },
        { name: "Congo", capital: "Brazzaville", continent: "Africa", flag: "https://flagcdn.com/cg.svg" },
        { name: "Congo (DRC)", capital: "Kinshasa", continent: "Africa", flag: "https://flagcdn.com/cd.svg" },
        { name: "Costa Rica", capital: "San José", continent: "North America", flag: "https://flagcdn.com/cr.svg" },
        { name: "Croatia", capital: "Zagreb", continent: "Europe", flag: "https://flagcdn.com/hr.svg" },
        { name: "Cuba", capital: "Havana", continent: "North America", flag: "https://flagcdn.com/cu.svg" },
        { name: "Cyprus", capital: "Nicosia", continent: "Europe", flag: "https://flagcdn.com/cy.svg" },
        { name: "Czech Republic", capital: "Prague", continent: "Europe", flag: "https://flagcdn.com/cz.svg" },
        { name: "Denmark", capital: "Copenhagen", continent: "Europe", flag: "https://flagcdn.com/dk.svg" },
        { name: "Djibouti", capital: "Djibouti", continent: "Africa", flag: "https://flagcdn.com/dj.svg" },
        { name: "Dominica", capital: "Roseau", continent: "North America", flag: "https://flagcdn.com/dm.svg" },
        { name: "Dominican Republic", capital: "Santo Domingo", continent: "North America", flag: "https://flagcdn.com/do.svg" },
        { name: "Ecuador", capital: "Quito", continent: "South America", flag: "https://flagcdn.com/ec.svg" },
        { name: "Egypt", capital: "Cairo", continent: "Africa", flag: "https://flagcdn.com/eg.svg" },
        { name: "El Salvador", capital: "San Salvador", continent: "North America", flag: "https://flagcdn.com/sv.svg" },
        { name: "Equatorial Guinea", capital: "Malabo", continent: "Africa", flag: "https://flagcdn.com/gq.svg" },
        { name: "Eritrea", capital: "Asmara", continent: "Africa", flag: "https://flagcdn.com/er.svg" },
        { name: "Estonia", capital: "Tallinn", continent: "Europe", flag: "https://flagcdn.com/ee.svg" },
        { name: "Eswatini", capital: "Mbabane", continent: "Africa", flag: "https://flagcdn.com/sz.svg" },
        { name: "Ethiopia", capital: "Addis Ababa", continent: "Africa", flag: "https://flagcdn.com/et.svg" },
        { name: "Fiji", capital: "Suva", continent: "Oceania", flag: "https://flagcdn.com/fj.svg" },
        { name: "Finland", capital: "Helsinki", continent: "Europe", flag: "https://flagcdn.com/fi.svg" },
        { name: "France", capital: "Paris", continent: "Europe", flag: "https://flagcdn.com/fr.svg" },
        { name: "Gabon", capital: "Libreville", continent: "Africa", flag: "https://flagcdn.com/ga.svg" },
        { name: "Gambia", capital: "Banjul", continent: "Africa", flag: "https://flagcdn.com/gm.svg" },
        { name: "Georgia", capital: "Tbilisi", continent: "Asia", flag: "https://flagcdn.com/ge.svg" },
        { name: "Germany", capital: "Berlin", continent: "Europe", flag: "https://flagcdn.com/de.svg" },
        { name: "Ghana", capital: "Accra", continent: "Africa", flag: "https://flagcdn.com/gh.svg" },
        { name: "Greece", capital: "Athens", continent: "Europe", flag: "https://flagcdn.com/gr.svg" },
        { name: "Grenada", capital: "Saint George's", continent: "North America", flag: "https://flagcdn.com/gd.svg" },
        { name: "Guatemala", capital: "Guatemala City", continent: "North America", flag: "https://flagcdn.com/gt.svg" },
        { name: "Guinea", capital: "Conakry", continent: "Africa", flag: "https://flagcdn.com/gn.svg" },
        { name: "Guinea-Bissau", capital: "Bissau", continent: "Africa", flag: "https://flagcdn.com/gw.svg" },
        { name: "Guyana", capital: "Georgetown", continent: "South America", flag: "https://flagcdn.com/gy.svg" },
        { name: "Haiti", capital: "Port-au-Prince", continent: "North America", flag: "https://flagcdn.com/ht.svg" },
        { name: "Honduras", capital: "Tegucigalpa", continent: "North America", flag: "https://flagcdn.com/hn.svg" },
        { name: "Hungary", capital: "Budapest", continent: "Europe", flag: "https://flagcdn.com/hu.svg" },
        { name: "Iceland", capital: "Reykjavik", continent: "Europe", flag: "https://flagcdn.com/is.svg" },
        { name: "India", capital: "New Delhi", continent: "Asia", flag: "https://flagcdn.com/in.svg" },
        { name: "Indonesia", capital: "Jakarta", continent: "Asia", flag: "https://flagcdn.com/id.svg" },
        { name: "Iran", capital: "Tehran", continent: "Asia", flag: "https://flagcdn.com/ir.svg" },
        { name: "Iraq", capital: "Baghdad", continent: "Asia", flag: "https://flagcdn.com/iq.svg" },
        { name: "Ireland", capital: "Dublin", continent: "Europe", flag: "https://flagcdn.com/ie.svg" },
        { name: "Israel", capital: "Jerusalem", continent: "Asia", flag: "https://flagcdn.com/il.svg" },
        { name: "Italy", capital: "Rome", continent: "Europe", flag: "https://flagcdn.com/it.svg" },
        { name: "Jamaica", capital: "Kingston", continent: "North America", flag: "https://flagcdn.com/jm.svg" },
        { name: "Japan", capital: "Tokyo", continent: "Asia", flag: "https://flagcdn.com/jp.svg" },
        { name: "Jordan", capital: "Amman", continent: "Asia", flag: "https://flagcdn.com/jo.svg" },
        { name: "Kazakhstan", capital: "Astana", continent: "Asia", flag: "https://flagcdn.com/kz.svg" },
        { name: "Kenya", capital: "Nairobi", continent: "Africa", flag: "https://flagcdn.com/ke.svg" },
        { name: "Kiribati", capital: "South Tarawa", continent: "Oceania", flag: "https://flagcdn.com/ki.svg" },
        { name: "Kuwait", capital: "Kuwait City", continent: "Asia", flag: "https://flagcdn.com/kw.svg" },
        { name: "Kyrgyzstan", capital: "Bishkek", continent: "Asia", flag: "https://flagcdn.com/kg.svg" },
        { name: "Laos", capital: "Vientiane", continent: "Asia", flag: "https://flagcdn.com/la.svg" },
        { name: "Latvia", capital: "Riga", continent: "Europe", flag: "https://flagcdn.com/lv.svg" },
        { name: "Lebanon", capital: "Beirut", continent: "Asia", flag: "https://flagcdn.com/lb.svg" },
        { name: "Lesotho", capital: "Maseru", continent: "Africa", flag: "https://flagcdn.com/ls.svg" },
        { name: "Liberia", capital: "Monrovia", continent: "Africa", flag: "https://flagcdn.com/lr.svg" },
        { name: "Libya", capital: "Tripoli", continent: "Africa", flag: "https://flagcdn.com/ly.svg" },
        { name: "Liechtenstein", capital: "Vaduz", continent: "Europe", flag: "https://flagcdn.com/li.svg" },
        { name: "Lithuania", capital: "Vilnius", continent: "Europe", flag: "https://flagcdn.com/lt.svg" },
        { name: "Luxembourg", capital: "Luxembourg City", continent: "Europe", flag: "https://flagcdn.com/lu.svg" },
        { name: "Madagascar", capital: "Antananarivo", continent: "Africa", flag: "https://flagcdn.com/mg.svg" },
        { name: "Malawi", capital: "Lilongwe", continent: "Africa", flag: "https://flagcdn.com/mw.svg" },
        { name: "Malaysia", capital: "Kuala Lumpur", continent: "Asia", flag: "https://flagcdn.com/my.svg" },
        { name: "Maldives", capital: "Malé", continent: "Asia", flag: "https://flagcdn.com/mv.svg" },
        { name: "Mali", capital: "Bamako", continent: "Africa", flag: "https://flagcdn.com/ml.svg" },
        { name: "Malta", capital: "Valletta", continent: "Europe", flag: "https://flagcdn.com/mt.svg" },
        { name: "Marshall Islands", capital: "Majuro", continent: "Oceania", flag: "https://flagcdn.com/mh.svg" },
        { name: "Mauritania", capital: "Nouakchott", continent: "Africa", flag: "https://flagcdn.com/mr.svg" },
        { name: "Mauritius", capital: "Port Louis", continent: "Africa", flag: "https://flagcdn.com/mu.svg" },
        { name: "Mexico", capital: "Mexico City", continent: "North America", flag: "https://flagcdn.com/mx.svg" },
        { name: "Micronesia", capital: "Palikir", continent: "Oceania", flag: "https://flagcdn.com/fm.svg" },
        { name: "Moldova", capital: "Chișinău", continent: "Europe", flag: "https://flagcdn.com/md.svg" },
        { name: "Monaco", capital: "Monaco", continent: "Europe", flag: "https://flagcdn.com/mc.svg" },
        { name: "Mongolia", capital: "Ulaanbaatar", continent: "Asia", flag: "https://flagcdn.com/mn.svg" },
        { name: "Montenegro", capital: "Podgorica", continent: "Europe", flag: "https://flagcdn.com/me.svg" },
        { name: "Morocco", capital: "Rabat", continent: "Africa", flag: "https://flagcdn.com/ma.svg" },
        { name: "Mozambique", capital: "Maputo", continent: "Africa", flag: "https://flagcdn.com/mz.svg" },
        { name: "Myanmar", capital: "Naypyidaw", continent: "Asia", flag: "https://flagcdn.com/mm.svg" },
        { name: "Namibia", capital: "Windhoek", continent: "Africa", flag: "https://flagcdn.com/na.svg" },
        { name: "Nauru", capital: "Yaren", continent: "Oceania", flag: "https://flagcdn.com/nr.svg" },
        { name: "Nepal", capital: "Kathmandu", continent: "Asia", flag: "https://flagcdn.com/np.svg" },
        { name: "Netherlands", capital: "Amsterdam", continent: "Europe", flag: "https://flagcdn.com/nl.svg" },
        { name: "New Zealand", capital: "Wellington", continent: "Oceania", flag: "https://flagcdn.com/nz.svg" },
        { name: "Nicaragua", capital: "Managua", continent: "North America", flag: "https://flagcdn.com/ni.svg" },
        { name: "Niger", capital: "Niamey", continent: "Africa", flag: "https://flagcdn.com/ne.svg" },
        { name: "Nigeria", capital: "Abuja", continent: "Africa", flag: "https://flagcdn.com/ng.svg" },
        { name: "North Korea", capital: "Pyongyang", continent: "Asia", flag: "https://flagcdn.com/kp.svg" },
        { name: "North Macedonia", capital: "Skopje", continent: "Europe", flag: "https://flagcdn.com/mk.svg" },
        { name: "Norway", capital: "Oslo", continent: "Europe", flag: "https://flagcdn.com/no.svg" },
        { name: "Oman", capital: "Muscat", continent: "Asia", flag: "https://flagcdn.com/om.svg" },
        { name: "Pakistan", capital: "Islamabad", continent: "Asia", flag: "https://flagcdn.com/pk.svg" },
        { name: "Palau", capital: "Ngerulmud", continent: "Oceania", flag: "https://flagcdn.com/pw.svg" },
        { name: "Palestine", capital: "Ramallah", continent: "Asia", flag: "https://flagcdn.com/ps.svg" },
        { name: "Panama", capital: "Panama City", continent: "North America", flag: "https://flagcdn.com/pa.svg" },
        { name: "Papua New Guinea", capital: "Port Moresby", continent: "Oceania", flag: "https://flagcdn.com/pg.svg" },
        { name: "Paraguay", capital: "Asunción", continent: "South America", flag: "https://flagcdn.com/py.svg" },
        { name: "Peru", capital: "Lima", continent: "South America", flag: "https://flagcdn.com/pe.svg" },
        { name: "Philippines", capital: "Manila", continent: "Asia", flag: "https://flagcdn.com/ph.svg" },
        { name: "Poland", capital: "Warsaw", continent: "Europe", flag: "https://flagcdn.com/pl.svg" },
        { name: "Portugal", capital: "Lisbon", continent: "Europe", flag: "https://flagcdn.com/pt.svg" },
        { name: "Qatar", capital: "Doha", continent: "Asia", flag: "https://flagcdn.com/qa.svg" },
        { name: "Romania", capital: "Bucharest", continent: "Europe", flag: "https://flagcdn.com/ro.svg" },
        { name: "Russia", capital: "Moscow", continent: "Europe", flag: "https://flagcdn.com/ru.svg" },
        { name: "Rwanda", capital: "Kigali", continent: "Africa", flag: "https://flagcdn.com/rw.svg" },
        { name: "Saint Kitts and Nevis", capital: "Basseterre", continent: "North America", flag: "https://flagcdn.com/kn.svg" },
        { name: "Saint Lucia", capital: "Castries", continent: "North America", flag: "https://flagcdn.com/lc.svg" },
        { name: "Saint Vincent and the Grenadines", capital: "Kingstown", continent: "North America", flag: "https://flagcdn.com/vc.svg" },
        { name: "Samoa", capital: "Apia", continent: "Oceania", flag: "https://flagcdn.com/ws.svg" },
        { name: "San Marino", capital: "San Marino", continent: "Europe", flag: "https://flagcdn.com/sm.svg" },
        { name: "Sao Tome and Principe", capital: "São Tomé", continent: "Africa", flag: "https://flagcdn.com/st.svg" },
        { name: "Saudi Arabia", capital: "Riyadh", continent: "Asia", flag: "https://flagcdn.com/sa.svg" },
        { name: "Senegal", capital: "Dakar", continent: "Africa", flag: "https://flagcdn.com/sn.svg" },
        { name: "Serbia", capital: "Belgrade", continent: "Europe", flag: "https://flagcdn.com/rs.svg" },
        { name: "Seychelles", capital: "Victoria", continent: "Africa", flag: "https://flagcdn.com/sc.svg" },
        { name: "Sierra Leone", capital: "Freetown", continent: "Africa", flag: "https://flagcdn.com/sl.svg" },
        { name: "Singapore", capital: "Singapore", continent: "Asia", flag: "https://flagcdn.com/sg.svg" },
        { name: "Slovakia", capital: "Bratislava", continent: "Europe", flag: "https://flagcdn.com/sk.svg" },
        { name: "Slovenia", capital: "Ljubljana", continent: "Europe", flag: "https://flagcdn.com/si.svg" },
        { name: "Solomon Islands", capital: "Honiara", continent: "Oceania", flag: "https://flagcdn.com/sb.svg" },
        { name: "Somalia", capital: "Mogadishu", continent: "Africa", flag: "https://flagcdn.com/so.svg" },
        { name: "South Africa", capital: "Pretoria", continent: "Africa", flag: "https://flagcdn.com/za.svg" },
        { name: "South Korea", capital: "Seoul", continent: "Asia", flag: "https://flagcdn.com/kr.svg" },
        { name: "South Sudan", capital: "Juba", continent: "Africa", flag: "https://flagcdn.com/ss.svg" },
        { name: "Spain", capital: "Madrid", continent: "Europe", flag: "https://flagcdn.com/es.svg" },
        { name: "Sri Lanka", capital: "Sri Jayawardenepura Kotte", continent: "Asia", flag: "https://flagcdn.com/lk.svg" },
        { name: "Sudan", capital: "Khartoum", continent: "Africa", flag: "https://flagcdn.com/sd.svg" },
        { name: "Suriname", capital: "Paramaribo", continent: "South America", flag: "https://flagcdn.com/sr.svg" },
        { name: "Sweden", capital: "Stockholm", continent: "Europe", flag: "https://flagcdn.com/se.svg" },
        { name: "Switzerland", capital: "Bern", continent: "Europe", flag: "https://flagcdn.com/ch.svg" },
        { name: "Syria", capital: "Damascus", continent: "Asia", flag: "https://flagcdn.com/sy.svg" },
        { name: "Taiwan", capital: "Taipei", continent: "Asia", flag: "https://flagcdn.com/tw.svg" },
        { name: "Tajikistan", capital: "Dushanbe", continent: "Asia", flag: "https://flagcdn.com/tj.svg" },
        { name: "Tanzania", capital: "Dodoma", continent: "Africa", flag: "https://flagcdn.com/tz.svg" },
        { name: "Thailand", capital: "Bangkok", continent: "Asia", flag: "https://flagcdn.com/th.svg" },
        { name: "Timor-Leste", capital: "Dili", continent: "Asia", flag: "https://flagcdn.com/tl.svg" },
        { name: "Togo", capital: "Lomé", continent: "Africa", flag: "https://flagcdn.com/tg.svg" },
        { name: "Tonga", capital: "Nuku'alofa", continent: "Oceania", flag: "https://flagcdn.com/to.svg" },
        { name: "Trinidad and Tobago", capital: "Port of Spain", continent: "North America", flag: "https://flagcdn.com/tt.svg" },
        { name: "Tunisia", capital: "Tunis", continent: "Africa", flag: "https://flagcdn.com/tn.svg" },
        { name: "Turkey", capital: "Ankara", continent: "Asia", flag: "https://flagcdn.com/tr.svg" },
        { name: "Turkmenistan", capital: "Ashgabat", continent: "Asia", flag: "https://flagcdn.com/tm.svg" },
        { name: "Tuvalu", capital: "Funafuti", continent: "Oceania", flag: "https://flagcdn.com/tv.svg" },
        { name: "Uganda", capital: "Kampala", continent: "Africa", flag: "https://flagcdn.com/ug.svg" },
        { name: "Ukraine", capital: "Kyiv", continent: "Europe", flag: "https://flagcdn.com/ua.svg" },
        { name: "United Arab Emirates", capital: "Abu Dhabi", continent: "Asia", flag: "https://flagcdn.com/ae.svg" },
        { name: "United Kingdom", capital: "London", continent: "Europe", flag: "https://flagcdn.com/gb.svg" },
        { name: "United States", capital: "Washington, D.C.", continent: "North America", flag: "https://flagcdn.com/us.svg" },
        { name: "Uruguay", capital: "Montevideo", continent: "South America", flag: "https://flagcdn.com/uy.svg" },
        { name: "Uzbekistan", capital: "Tashkent", continent: "Asia", flag: "https://flagcdn.com/uz.svg" },
        { name: "Vanuatu", capital: "Port Vila", continent: "Oceania", flag: "https://flagcdn.com/vu.svg" },
        { name: "Vatican City", capital: "Vatican City", continent: "Europe", flag: "https://flagcdn.com/va.svg" },
        { name: "Venezuela", capital: "Caracas", continent: "South America", flag: "https://flagcdn.com/ve.svg" },
        { name: "Vietnam", capital: "Hanoi", continent: "Asia", flag: "https://flagcdn.com/vn.svg" },
        { name: "Yemen", capital: "Sana'a", continent: "Asia", flag: "https://flagcdn.com/ye.svg" },
        { name: "Zambia", capital: "Lusaka", continent: "Africa", flag: "https://flagcdn.com/zm.svg" },
        { name: "Zimbabwe", capital: "Harare", continent: "Africa", flag: "https://flagcdn.com/zw.svg" }
    ];
    return (<div className="container">
        <div className="row">
            {countries.map((item) => {
                return <Country name={item.name} flag={item.flag} capital={item.capital}
                    currency={item.currency} continent={item.continent} />
            })}
        </div>

    </div>
    );
}
const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(<World />)